name: GitHub Actions Demo
on: [push]
jobs:
  gh-action:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

  gh-action1:
    needs: gh-action
    runs-on: ubuntu-latest
    steps:
      - run: echo "completed"

  gh-action2:
    needs: gh-action1
    runs-on: ubuntu-latest
    steps:
      - run: echo "completed gh-action1"
